### PR TITLE
FEAT lightgbm methods

### PR DESCRIPTION
**Pull request by rosemary-tawn-tnei**
Functions for lightgbm (qreg, predict, print, summary)
Also function for periodic retraining and updating over the Test fold

### CODE REVIEW

**Review by jbrowell — CHANGES_REQUESTED** [review]
Thanks! Looks good, though I haven't examined every line... Please can you add a few quick things:
1. Run `document()` to update the package documentation based on your roxygen docs and check this is all as intended
2. Add example usage to `Example.R`
3. Add necessary dependencies to `DESCRIPTION`

**Comment by rosemary-tawn-tnei** [comment]
I've made those changes now! :)

**Review by jbrowell — CHANGES_REQUESTED** [review]
Thanks! Looks great and I've been able to run the example with no problem (once I installed the right version of lightgbm. One tiny think I spotted: the argument to the retraining function `issue_datetime_column` isn't documented.

**Comment by rosemary-tawn-tnei** [comment]
Well spotted- I've updated that now!

**Review by jbrowell — APPROVED** [review]
Great - thanks!

**Pull request merged**
